spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa


  jpa:
    properties:
      hibernate:
        format_sql: true
        user_sql_coments: true

    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      apache:
        coyote:
          http11: debug

      hiberante:
        SQL: debug

    board:
      myboard: info
